const CONTEXT_TYPE = "geographicContext";
const BUILDING_TYPE = "geographicBuilding";
const FLOOR_TYPE = "geographicFloor";
const ZONE_TYPE = "geographicZone";
const ROOM_TYPE = "geographicRoom";
const EQUIPMENT_TYPE = "BIMObject";


//relations
const BUILDING_RELATION = "hasGeographicBuilding";
const FLOOR_RELATION = "hasGeographicFloor";
const ZONE_RELATION = "hasGeographicZone";
const ROOM_RELATION = "hasGeographicRoom";
const EQUIPMENT_RELATION = "hasBIMObject";


const GEOGRAPHIC_TYPES = Object.freeze([
  BUILDING_TYPE,
  FLOOR_TYPE,
  ZONE_TYPE,
  ROOM_TYPE
]);


const GEOGRAPHIC_TYPES_ORDER = Object.freeze([
  CONTEXT_TYPE,
  BUILDING_TYPE,
  FLOOR_TYPE,
  ZONE_TYPE,
  ROOM_TYPE,
  EQUIPMENT_TYPE
]);


const GEOGRAPHIC_RELATIONS = Object.freeze([
  BUILDING_RELATION,
  FLOOR_RELATION,
  ZONE_RELATION,
  ROOM_RELATION
]);

const GEOGRAPHIC_RELATIONS_ORDER = Object.freeze([
  BUILDING_RELATION,
  FLOOR_RELATION,
  ZONE_RELATION,
  ROOM_RELATION,
  EQUIPMENT_RELATION
]);

const MAP_TYPE_RELATION = Object.freeze(new Map([
  [BUILDING_TYPE, BUILDING_RELATION],
  [FLOOR_TYPE, FLOOR_RELATION],
  [ZONE_TYPE, ZONE_RELATION],
  [ROOM_TYPE, ROOM_RELATION],
  [EQUIPMENT_TYPE, EQUIPMENT_RELATION]
]));

const MAP_RELATION_TYPE = Object.freeze(new Map([
  [BUILDING_RELATION, BUILDING_TYPE],
  [FLOOR_RELATION, FLOOR_TYPE],
  [ZONE_RELATION, ZONE_TYPE],
  [ROOM_RELATION, ROOM_TYPE],
  [EQUIPMENT_RELATION, EQUIPMENT_TYPE]
]));

export {
  CONTEXT_TYPE,
  BUILDING_TYPE,
  FLOOR_TYPE,
  ZONE_TYPE,
  ROOM_TYPE,
  GEOGRAPHIC_TYPES,
  EQUIPMENT_TYPE,
  GEOGRAPHIC_TYPES_ORDER,
  BUILDING_RELATION,
  FLOOR_RELATION,
  ZONE_RELATION,
  ROOM_RELATION,
  GEOGRAPHIC_RELATIONS,
  EQUIPMENT_RELATION,
  GEOGRAPHIC_RELATIONS_ORDER,
  MAP_TYPE_RELATION,
  MAP_RELATION_TYPE
};